### ISSUE TITLE
No way to set OFF to remove characters

### ISSUE THREAD

**Issue by newbialywhodis** [JGUsman007/esx_multicharacter-redesign#1]
Hi, is there a way you could fix Config.CanDelete = false?
Delete character button doesnt hide with this config

**Comment by amgmacht** [comment]
I have taken out everything concerning the deletion of characters and it works great :). So you can do it even if you already want to disable it.

**Comment by amgmacht** [comment]
> Hi, is there a way you could fix Config.CanDelete = false? Delete character button doesnt hide with this config

Check the pull request there you might find a solution for your problem ^^

**Comment by AfterLifeStudio** [comment]
download the new update
